const readings = [
  {
    title: "Introducing Curation Markets",
    date: "2017",
    author: "Simon de la Rouviere",
    excerpt: "Each topic/meme/idea/goal has an associated token of value that is used to curate information inside it.  Using Ethereum as a programmable, distributed, shared ledger, these groups can mint a token of value according to agreed upon rules without a centralized 3rd party being involved. In other words, a specific entity is not involved in the creation process of the tokens of value..",
    topic: "Mechanism Design",
    slug: "https://medium.com/@simondlr/introducing-curation-markets-trade-popularity-of-memes-information-with-code-70bf6fed9881",
  },
  {
    title: "Are Markets Efficient?",
    date: "2016",
    author: "Fama & Thaler",
    excerpt: "Many economists view financial markets as efficient, with prices incorporating all information about future values. Behavioral economists say that model simply doesn’t reflect how markets actually work. So are markets efficient?",
    topic: "Economics",
    slug: "https://www.chicagobooth.edu/review/are-markets-efficient",
  },
  {
    title: "Zero to One",
    date: "2014",
    author: "Theil & Masters",
    excerpt: "Competition can make people hallucinate opportunities where none exist.",
    topic: "Startups",
    slug: "https://www.amazon.com/Zero-One-Notes-Startups-Future/dp/0804139296",
  },
  {
    title: "Squad Wealth",
    date: "2020",
    author: "Hart, Shorin & Lotti",
    excerpt: `Group identity. Shared space. Vibes. These not only enable the creation of social capital, but strengthen the squad's capacity to organize, minimizing transaction costs and leading to greater productive capacities and resilience; this is "the nature of the squad." But while squads can be viewed as a "nexus of contracts", unlike the Coasean firm, they are without legal structure. Social contracts are instead effected through the unspoken bonds of mutual respect and ingroup norms.`,
    topic: "Coordination",
    slug: "https://otherinter.net/research/squad-wealth/",
  },
  {
    title: "A Guide to Designing Effective NFT Launches",
    date: "2021",
    author: "Hasu & Agnihotri",
    excerpt: `Most of these launches employed a fixed-price, first-come-first-served (FCFS) mechanism. With low prices and excessive demand, competition to acquire such NFTs transitioned from the contract sale to a gas auction in the mempool.`,
    topic: "Mechanism Design",
    slug: "https://www.paradigm.xyz/2021/10/a-guide-to-designing-effective-nft-launches",
  },
  {
    title: "A Deep Dive into Rollups",
    date: "2022",
    author: "Barnabé Monnot",
    excerpt: `These two items, verifiable settlement and data availability, are critical to secure off-chain execution. The first effectively ensures that theft cannot be committed. The second provides certainty that any attempt to settle stale state can be successfully challenged.  Rollups are off-chain networks built to satisfy both properties.`,
    topic: "Mechanism Design",
    slug: "https://nodeguardians.io/dev-hub/quests/rollups",
  },
  {
    title: "Small Applications, Growing Protocols",
    date: "2023",
    author: "Packy McCormick",
    excerpt: `But I think there might be another, third way. Small Apps that recognize their fleeting nature can team up with protocols that are built to last to build something bigger and more durable collectively.`,
    topic: "Frameworks",
    slug: "https://www.notboring.co/p/small-applications-growing-protocols",
  },
  {
    title: "Interoperability and Market Segmentation",
    date: "2022",
    author: "Stephen McKeon",
    excerpt: `The immediate observation is that traders on the Avalanche market are worse off, since the price is better on the Ethereum market. But the more important insight is that market participants in both markets are worse off relative to markets with pooled liquidity.`,
    topic: "Mechanism Design",
    slug: "https://medium.com/collab-currency/interoperability-and-market-segmentation-9cd098382414",
  },
  {
    title: "Analyzing Stock Market Movements Using Twitter",
    date: "2012",
    author: "Rao & Srivastava",
    excerpt: `Where Mt^Positive and Mt^Negative represent number of positive or negative tweets on a particular day t. Logarithm of bullishness measures the share of surplus positive signals and also gives more weight to larger number of messages in a specific sentiment (positive or negative). Message volume for a time interval t is simply defined as natural logarithm of total number of tweets for a specific stock/index which is ln(Mt^Positive+Mt^Negative). The agreement among positive and negative tweet messages is defined by:`,
    topic: "Economics",
    slug: "https://dl.acm.org/doi/pdf/10.5555/2456719.2456923",
  },
]

export default readings